build:
    nodes:
        php74:
            environment:
                php:
                    version: 7.4
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit'

        php8:
            environment:
                php:
                    version: 8.0
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit'
